### ISSUE TITLE
Btd error (JSON Parse error: Unexpected EOF (-2700))

### ISSUE THREAD

**Issue by pavzagor** [vitorgalvao/dente-azul-workflow#3]
### Workflow version

2023.5

### Alfred version

5.1.3 [2175]

### macOS version

14.0 (23A344)

### Debugger output

```alfred_debugger
ERROR: Dente Azul[Script Filter] Code 1: /Users/pavelzagorodnikh/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/BE0F737C-BFC9-4776-8544-5B57443CFD2E: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
```

### More details

Expected to see bluetooth device list.
Debugger info attached.

Video: https://www.loom.com/share/0351620c7ead40888ab3acf26ad317cf?sid=b27854b1-6593-4d3a-acdc-244ba724c22b

**Comment by vitorgalvao** [comment]
You have to [install the dependencies](https://www.alfredapp.com/help/kb/dependencies/). This is explained at the top of [the Gallery page](https://alfred.app/workflows/vitor/dente-azul/).

**Comment by marcelotto** [comment]
I've had the same issue after upgrading to Sonoma. I had to allow Alfred to use Bluetooth in the new Privacy & Security section.

**Comment by vitorgalvao** [comment]
The section is not new, it has been there for a few macOS versions already. But for some reason only with Sonoma did it start being necessary for `blueutil`.

**Comment by pavzagor** [comment]
Worked, thanks!

**Comment by JosefGvirt** [comment]
> I had the same issue after upgrading to Sonoma. I had to allow Alfred to use Bluetooth in the new Privacy & Security section of the system settings.

Just tried this myself, seems to fix the issue.

**Comment by roele** [comment]
Maybe a hint/section in the README would be helpful

**Comment by vitorgalvao** [comment]
Version 2023.6, just released, now detects if permission is missing.

<img width="646" src="https://github.com/vitorgalvao/dente-azul-workflow/assets/1699443/70b942e5-7753-42ad-a098-6c7f191765f4">
