### ISSUE TITLE
Doesn't work on Mac OS sonoma

### ISSUE THREAD

**Issue by JosefGvirt** [vitorgalvao/dente-azul-workflow#4]
### Workflow version

2023.5

### Alfred version

5.1.3

### macOS version

sonoma 14.0

### Debugger output

```alfred_debugger
The workflow doesn't work on Mac OS Sonoma 14.0; whenever I try to run the Keyword BTD in the Alfred search, it doesn't show the Bluetooth devices.
```

### More details

The workflow doesn't work on Mac OS Sonoma 14.0; whenever I try to run the Keyword BTD in the Alfred search, it doesn't show the Bluetooth devices.

**Comment by vitorgalvao** [comment]
See https://github.com/vitorgalvao/dente-azul-workflow/issues/3#issuecomment-1747793423.

For future issues, please add the correct [debugger output](https://www.alfredapp.com/help/workflows/advanced/debugger/). Without that it’s hard to diagnose issues.
